
# Cinder
- tempest.api.compute.servers.test_server_rescue_negative.ServerRescueNegativeTestJSON.test_rescued_vm_detach_volume[id-f56e465b-fe10-48bf-b75d-646cda3a8bc9,negative,volume]:
    Fail because of https://bugs.launchpad.net/mos/+bug/1478259
- tempest.api.volume.admin.test_volumes_backup.VolumesBackupsV1Test.test_volume_backup_export_import[id-a99c54a1-dd80-4724-8a13-13bf58d4068d]:
    Fail because of https://bugs.launchpad.net/mos/+bug/1478062
- tempest.api.volume.admin.test_volumes_backup.VolumesBackupsV2Test.test_volume_backup_export_import[id-a99c54a1-dd80-4724-8a13-13bf58d4068d]:
    Fail because of https://bugs.launchpad.net/mos/+bug/1478062
